### ISSUE TITLE
add_pos_embedding 函数中x的维度不匹配问题

### ISSUE THREAD

**Issue by keaill** [Chen-Yang-Liu/RSCaMa#4]
![image](https://github.com/user-attachments/assets/b54d1022-8802-4779-82fb-3b1abf2cac48)
![image](https://github.com/user-attachments/assets/4cc9a2a9-afca-4380-92c0-bad674a48b64)
您好！我在运行您的代码的时候，add_pos_embedding中的x是二维的，打印出来的维度是[64, 768]，因此出现了not enough values to unpack (expected 4, got 2)问题，请问您知道这种问题怎么解决吗？

**Comment by leyuan-sun** [comment]
FYI：https://github.com/Chen-Yang-Liu/PromptCC/issues/3

**Comment by keaill** [comment]
> FYI：[Chen-Yang-Liu/PromptCC#3](https://github.com/Chen-Yang-Liu/PromptCC/issues/3)

嗯嗯clip的源码我修改过了，还是出现这个问题
